### ISSUE TITLE
[Request] History

### ISSUE THREAD

**Issue by Kastrel7** [jjbankert/hass_chatgpt#12]
Add ability to save history of chat to a json file to come back to later. Could be a parameter in the service called "conversation" which much have the same name as the json file in which the history of the conversation is saved.

**Comment by jjbankert** [comment]
Hi,

could you explain the use case for this? Currently I look in the automation/script traces to look back at what happened. I added this to my `say_with_gpt` script:
```
trace:
  stored_traces: 100
```

**Comment by Kastrel7** [comment]
The use of this is for followup questions or questions about the same topic that uses the past questions and answers as logic. It saves the user input and the assistant output.

**Comment by jjbankert** [comment]
Ah, maybe the conversation agents built into Home Assistant will help you reach your goal. I'm discontinuing the project because my personal use-cases are now covered by those conversation agents and service responses in the latest Home Assistant release. 

See the README for my suggested migration option.
