### ISSUE TITLE
Stopped working on Homeassistant 2023.6

### ISSUE THREAD

**Issue by TNTLarsn** [jjbankert/hass_chatgpt#6]
> Package chatgpt setup failed. Component chatgpt Requirements for chatgpt not found: ['requests==2.28.2'].

**Comment by johnwalk61** [comment]
> > Package chatgpt setup failed. Component chatgpt Requirements for chatgpt not found: ['requests==2.28.2'].

Same issue after 2023.6
TNTLarsn's fix corrected the error. Working well now. Thanks man

**Comment by antisane** [comment]
Same as above.

Home Assistant 2023.6.0
Supervisor 2023.06.1
Operating System 10.2
Frontend 20230607.0 - latest

I've had this working for a few weeks now, but now Home Assistant does not like the confuration.yaml entry at all. 
If I remove it I can reboot HAOS with no issues, but if I put it back (the way it worked before) I get an invalid config entry error and cannot restart Home Assistant.

`Error executing service: <ServiceCall homeassistant.restart (c:01H2DPXYD8ST05CHTCFP06V2P6)>
10:35:35 AM – (ERROR) components/hassio/__init__.py

The system cannot restart because the configuration is not valid: Integration error: chatgpt - Requirements for chatgpt not found: ['requests==2.28.2'].
10:35:35 AM – (ERROR) Home Assistant Supervisor

Unable to install package requests==2.28.2: ERROR: Cannot install requests==2.28.2 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
10:35:35 AM – (ERROR) util/package.py - message first occurred at 10:35:26 AM and shows up 3 times`

**Comment by TNTLarsn** [comment]
> Same as above.
> 
> Home Assistant 2023.6.0 Supervisor 2023.06.1 Operating System 10.2 Frontend 20230607.0 - latest
> 
> I've had this working for a few weeks now, but now Home Assistant does not like the confuration.yaml entry at all. If I remove it I can reboot HAOS with no issues, but if I put it back (the way it worked before) I get an invalid config entry error and cannot restart Home Assistant.
> 
> `Error executing service: <ServiceCall homeassistant.restart (c:01H2DPXYD8ST05CHTCFP06V2P6)> 10:35:35 AM – (ERROR) components/hassio/**init**.py
> 
> The system cannot restart because the configuration is not valid: Integration error: chatgpt - Requirements for chatgpt not found: ['requests==2.28.2']. 10:35:35 AM – (ERROR) Home Assistant Supervisor
> 
> Unable to install package requests==2.28.2: ERROR: Cannot install requests==2.28.2 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts 10:35:35 AM – (ERROR) util/package.py - message first occurred at 10:35:26 AM and shows up 3 times`

1. Change the manifest.json in your `custom_components/chatgpt` folder like [this](https://github.com/jjbankert/hass_chatgpt/pull/7/files)
2. comment out `chatgpt:` in your configuration.yaml (in order to restart homeassistant)
3. restart homeassistant
4. remove the comments you have set in step 2
5. restart homeassistant again.
6. should work now...


**OR:** just wait until my PR https://github.com/jjbankert/hass_chatgpt/pull/7 has been merged an a new release has been published. Then update this Custom Component via HACS

**Comment by jjbankert** [comment]
Thanks for the heads up!

**Comment by antisane** [comment]
All working for me now, thanks!
